#!/usr/bin/env bash
set -euo pipefail
pid=""

_int() {
  echo "INT (reflex-wrapper) -> killing PID $pid"
  kill $pid || true
  wait $pid || true

  echo "EXIT 0 (reflex-wrapper)"
  exit 0
}

trap '_int' INT

while true; do
  set +e
    $@ &
    pid=$!
    wait $pid
  set -e

  echo ""
  echo "-- restart"
  sleep 0.1
done
